[settings]
timeout = 1000

[relaychain]
default_image = "{{ZOMBIENET_INTEGRATION_TEST_IMAGE}}"
chain = "rococo-local"

[relaychain.default_resources]
limits = { memory = "4G", cpu = "2" }
requests = { memory = "2G", cpu = "1" }

  [[relaychain.nodes]]
  # Use an image that doesn't use validation v3 protocol.
  image = "{{POLKADOT_IMAGE}}:master-4ac9c4a3"
  name = "alice"
  args = [ "--alice", "-lparachain=debug,runtime=debug" ]

  [[relaychain.nodes]]
  name = "bob"
  args = [ "--bob", "-lparachain=debug,runtime=debug"]

  [[relaychain.nodes]]
  name = "charlie"
  args = [ "--charlie", "-lparachain=debug,runtime=debug" ]

  [[relaychain.nodes]]
  name = "dave"
  args = [ "--dave", "-lparachain=debug,runtime=debug"]

  [[relaychain.nodes]]
  name = "ferdie"
  args = [ "--ferdie", "-lparachain=debug,runtime=debug" ]

  [[relaychain.nodes]]
  name = "eve"
  args = [ "--eve", "-lparachain=debug,runtime=debug"]

  [[relaychain.nodes]]
  name = "one"
  args = [ "--one", "-lparachain=debug,runtime=debug" ]

  [[relaychain.nodes]]
  name = "two"
  args = [ "--two", "-lparachain=debug,runtime=debug"]

[[parachains]]
id = 2000
addToGenesis = true
genesis_state_generator = "adder-collator export-genesis-state"

  [parachains.collator]
  name = "collator01"
  image = "{{COL_IMAGE}}"
  command = "adder-collator"
  args = ["-lparachain=debug", "--parachain-id=2000"]

[[parachains]]
id = 2001
addToGenesis = true
genesis_state_generator = "adder-collator export-genesis-state"

  [parachains.collator]
  name = "collator02"
  image = "{{COL_IMAGE}}"
  command = "adder-collator"
  args = ["-lparachain=debug", "--parachain-id=2001"]

[[parachains]]
id = 2002
addToGenesis = true
genesis_state_generator = "adder-collator export-genesis-state"

  [parachains.collator]
  name = "collator03"
  image = "{{COL_IMAGE}}"
  command = "adder-collator"
  args = ["-lparachain=debug", "--parachain-id=2002"]

[[parachains]]
id = 2003
addToGenesis = true
genesis_state_generator = "adder-collator export-genesis-state"

  [parachains.collator]
  name = "collator04"
  image = "{{COL_IMAGE}}"
  command = "adder-collator"
  args = ["-lparachain=debug", "--parachain-id=2003"]

[[parachains]]
id = 2004
addToGenesis = true
genesis_state_generator = "adder-collator export-genesis-state"

  [parachains.collator]
  name = "collator05"
  image = "{{COL_IMAGE}}"
  command = "adder-collator"
  args = ["-lparachain=debug", "--parachain-id=2004"]

[[parachains]]
id = 2005
addToGenesis = true
genesis_state_generator = "adder-collator export-genesis-state"

  [parachains.collator]
  name = "collator06"
  image = "{{COL_IMAGE}}"
  command = "adder-collator"
  args = ["-lparachain=debug", "--parachain-id=2005"]

[[parachains]]
id = 2006
addToGenesis = true
genesis_state_generator = "adder-collator export-genesis-state"

  [parachains.collator]
  name = "collator07"
  image = "{{COL_IMAGE}}"
  command = "adder-collator"
  args = ["-lparachain=debug", "--parachain-id=2006"]

[[parachains]]
id = 2007
addToGenesis = true
genesis_state_generator = "adder-collator export-genesis-state"

  [parachains.collator]
  name = "collator08"
  image = "{{COL_IMAGE}}"
  command = "adder-collator"
  args = ["-lparachain=debug", "--parachain-id=2007"]

[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"
